home:
  link_index: "index.html"
  remember: "1"
shop:
  footer:
    copyright: "Copyright 2020 © Shopee All rights reserved."
    madeby: "Made by Sun Asterisk"
  file_type: "image/jpeg image/jpg image/png"
  name_max_length: 255
  description_max_length: 10240
  dollar: 24000
  color_b00: "#b00"
  color_666: "#666"
  price_min: 0
  price_max: 20000000
  quantity_max: 1000
  product_per_page: 50
reg:
  email: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
name:
  maximum: 50
email:
  maximum: 255
record_per_page: 4
password:
  minimum: 6
length_input: 80
user_mail: "https://gravatar.com/emails"
paginate_theme: "twitter-bootstrap-3"
size_avatar: 50
norep_email: "Anhlinh12369@icloud.com"
max_content: 140
size_max: 5
resize_to_limit: "100x100"
price_100: 100
price_200: 200
parent_category: 0
quantity_min: 0
